default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: 5
  username: root
  password: *****
  host: localhost

development:
  <<: *default
  database: kula_project_development

test:
  <<: *default
  database: kula_project_test

production:
  <<: *default
  database: kula_project_production
  username: root
  password: <%= ENV['KULA_DATABASE_PASSWORD'] %>
